make the CMakeLists.txt valid for Windows system
For windows os, i try use CMake to generate project file for visual
studio, but if NV_OS_DARWIN is defined, we get error during compiling:
6>D:\Users\renc\Documents\GitHub\thekla_atlas\src\nvcore\Stream.h(82):
error C2466: cannot allocate an array of constant size 0

to fix that compile error, we only need to ignore this macro for windows
os.

after this fix, this project can use cmake to generate project file on
windows too, in that case, the projects/vc9/ folder can be removed i
think.